//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParcInfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class observation
    {
        public int Id { get; set; }
        public Nullable<int> IdIntervention { get; set; }
        public string IdUser { get; set; }
        public string TypeOb { get; set; }
        public string Textobservation { get; set; }
        public System.DateTime Dateobservation { get; set; }
        public string Detailproduit { get; set; }
        public Nullable<int> IsDeleted { get; set; }
    
        public virtual Intervention Intervention { get; set; }
    }
}
