//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParcInfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParametreParcinfo
    {
        public string Nomapp { get; set; }
        public byte[] Logoapp { get; set; }
        public Nullable<int> Reatrddemande { get; set; }
        public byte[] Iconapp { get; set; }
    }
}
