//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParcInfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProduitClient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProduitClient()
        {
            this.Installers = new HashSet<Installer>();
            this.Installers1 = new HashSet<Installer>();
            this.ProduitUtilisers = new HashSet<ProduitUtiliser>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> Dateaffectation { get; set; }
        public Nullable<double> Prixvente { get; set; }
        public Nullable<int> Idclient { get; set; }
        public Nullable<int> Idproduit { get; set; }
        public Nullable<int> ParIntervention { get; set; }
        public Nullable<System.DateTime> Datemodification { get; set; }
        public Nullable<int> Creepar { get; set; }
        public Nullable<int> Modifierpar { get; set; }
        public int IsDeleted { get; set; }
    
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Installer> Installers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Installer> Installers1 { get; set; }
        public virtual Intervention Intervention { get; set; }
        public virtual Produit Produit { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
        public virtual Utilisateur Utilisateur1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProduitUtiliser> ProduitUtilisers { get; set; }
    }
}
